### ISSUE TITLE
auto-detect local game?

### ISSUE THREAD

**Issue by subtledoctor** [AstroBryGuy/NearInfinity-OSX#2]
Whenever I open any instance of NI, from any directory, it remembers the last game I had open. If I want to inspect the files in a different game - including the game in the same directory as this instance of NI - I have to go to the menu and select "open" and then choose a chitin.key from the dialogue. Is there a setting anywhere that will make NI open the copy of chitin.key in the same folder as the copy of the NI executable I am running? This is how it used to behave, and it was more convenient - when I wanted to look at my IWDEE files, I would run the copy of NI in the IWDEE folder; when I wanted to look at my SoD files, I would run the copy of NI in the SoD folder; etc.

**Comment by AstroBryGuy** [comment]
This is apparently a consequence of how launching a packaged application works on macOS. It sets the working directory to the user's home directory (useful if the app was launched from /Applications/). I'm not able to change the working directory after launch.

The old launcher was a just a shell script that invoked the user's existing Java install. The new version is an actual packaged app, created with jpackage, so that NI can request access the Documents folder (and be able to see the saved game and portrait folders). The shell script version stopped being able to access the Documents folder on recent versions of macOS, hence the change to jpackage.

If you don't care about accessing saved games and need something that works the way you want, you can always pull the old shell script version out of the GitHub history and just replace NearInfinity.jar with the latest version in the package.
